[workspace]
members = [
    "packages/matcher-common",
    "programs/privacy-matcher",
    "programs/vol-matcher",
    "programs/jpy-matcher",
    "programs/event-matcher",
    "programs/macro-matcher",
]
resolver = "2"
